# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_code', models.IntegerField()),
                ('seqnr', models.IntegerField()),
                ('stop_nr', models.IntegerField()),
                ('full_name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=5)),
                ('zone', models.CharField(max_length=6)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('zone_nr_1', models.IntegerField()),
                ('zone_nr_2', models.IntegerField()),
                ('stop_type', models.IntegerField()),
                ('reboard_time', models.IntegerField()),
                ('stop_class', models.IntegerField()),
            ],
        ),
    ]
