# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=128)),
                ('stop_desc', models.CharField(max_length=128)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('stop_url', models.CharField(max_length=128)),
            ],
        ),
    ]
