# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
